# Generated by Django 4.1.5 on 2023-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ImageField(upload_to='ppic')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
        ),
    ]
